<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWxRTcUy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWxRTcUy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWxRTcUy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWxRTcUy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWxRTcUy\App_KernelDevDebugContainer([
    'container.build_hash' => 'WxRTcUy',
    'container.build_id' => 'cac12445',
    'container.build_time' => 1632842498,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWxRTcUy');
